name: Check for new releases

on:
  schedule:
  - cron: "0 * * * *"

jobs:
  new-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: get-latest-version
      run: |
        VERSION="$(curl --silent --show-error --location https://www.gog.com/galaxy \
          | grep 'https://content-system\.gog\.com/open_link/download?path=/open/galaxy/client/setup_galaxy.*\.exe' \
          | head -n1 \
          | sed -E -e 's|^.*"https://content-system\.gog\.com/open_link/download\?path=/open/galaxy/client/setup_galaxy_(.*)\.exe".*$|\1|')"
        EDGEVER="$(snap info gog-galaxy-wine | awk '$1 == "edge:" { print $2 }')"
        if [ "$VERSION" != "$EDGEVER" ]; then
          echo "$(date -u --rfc-3339=seconds) Version $VERSION" >> .build.stamp
        fi
    - uses: stefanzweifel/git-auto-commit-action@v2.1.0
      with:
        commit_message: Trigger build for new version
        branch: ${{ github.head_ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
